# Generated by Django 5.1 on 2024-08-13 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task1", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Buyer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=100)),
                ("balance", models.IntegerField()),
            ],
        ),
    ]
